PACKAGE_NAME="batman-adv"
PACKAGE_VERSION="2026.2"
MAKE[0]="make -C batman-adv -j$(nproc) KERNELPATH=${kernel_source_dir}"
CLEAN="make -C batman-adv clean"
BUILT_MODULE_NAME[0]="batman-adv"
BUILT_MODULE_LOCATION[0]="batman-adv/net/batman-adv"
DEST_MODULE_LOCATION[0]="/updates/net/batman-adv"
AUTOINSTALL="yes"
